"""
Abbreviation -> expansion mappings for preprocessing.

Keys are lowercased. Values are the expanded canonical form.
Covers common abbreviations in real estate, electronics, automotive,
services, and general marketplace contexts.
"""

ABBREVIATIONS = {
    # Electronics / Computing
    "ac": "air conditioning",
    "tv": "television",
    "pc": "personal computer",
    "ssd": "solid state drive",
    "hdd": "hard disk drive",
    "gpu": "graphics processing unit",
    "cpu": "central processing unit",
    "ram": "random access memory",
    "lcd": "liquid crystal display",
    "led": "light emitting diode",
    "oled": "organic light emitting diode",
    "usb": "universal serial bus",
    "hdmi": "high definition multimedia interface",
    "wifi": "wireless fidelity",
    "wi-fi": "wireless fidelity",
    "bt": "bluetooth",
    "nfc": "near field communication",
    "gps": "global positioning system",
    "os": "operating system",
    "ui": "user interface",
    "ux": "user experience",
    "ai": "artificial intelligence",
    "ml": "machine learning",
    "iot": "internet of things",
    "vr": "virtual reality",
    "ar": "augmented reality",
    "ups": "uninterruptible power supply",
    "psu": "power supply unit",
    "dvd": "digital versatile disc",
    "cd": "compact disc",
    "fps": "frames per second",

    # Real Estate / Housing
    "bhk": "bedroom hall kitchen",
    "1bhk": "1 bedroom hall kitchen",
    "2bhk": "2 bedroom hall kitchen",
    "3bhk": "3 bedroom hall kitchen",
    "4bhk": "4 bedroom hall kitchen",
    "1rk": "1 room kitchen",
    "pg": "paying guest",
    "sqft": "square feet",
    "sq ft": "square feet",
    "sq.ft": "square feet",
    "sqm": "square meters",
    "apt": "apartment",
    "bldg": "building",
    "flr": "floor",
    "furn": "furnished",
    "unfurn": "unfurnished",
    "semifurn": "semi furnished",
    "emi": "equated monthly installment",
    "rcc": "reinforced cement concrete",
    "hvac": "heating ventilation and air conditioning",

    # Automotive
    "suv": "sport utility vehicle",
    "mpv": "multi purpose vehicle",
    "muv": "multi utility vehicle",
    "hb": "hatchback",
    "cng": "compressed natural gas",
    "lpg": "liquefied petroleum gas",
    "ev": "electric vehicle",
    "bev": "battery electric vehicle",
    "phev": "plug in hybrid electric vehicle",
    "hev": "hybrid electric vehicle",
    "fwd": "front wheel drive",
    "rwd": "rear wheel drive",
    "awd": "all wheel drive",
    "4wd": "four wheel drive",
    "abs": "anti lock braking system",
    "airbag": "air bag",
    "cc": "cubic centimeters",
    "rpm": "revolutions per minute",
    "kmpl": "kilometers per liter",
    "mpg": "miles per gallon",
    "amt": "automated manual transmission",
    "cvt": "continuously variable transmission",
    "dct": "dual clutch transmission",
    "dsg": "direct shift gearbox",
    "turbo": "turbocharged",
    "tdi": "turbocharged direct injection",
    "gdi": "gasoline direct injection",
    "crdi": "common rail direct injection",
    "bs6": "bharat stage 6",
    "bs4": "bharat stage 4",
    "drl": "daytime running lights",
    "orvm": "outside rear view mirror",
    "irvm": "inside rear view mirror",
    "esc": "electronic stability control",
    "tcs": "traction control system",
    "eps": "electric power steering",
    "adas": "advanced driver assistance system",

    # General Services / Professions
    "hr": "human resources",
    "it": "information technology",
    "bpo": "business process outsourcing",
    "ca": "chartered accountant",
    "cs": "company secretary",
    "mbbs": "bachelor of medicine bachelor of surgery",
    "bds": "bachelor of dental surgery",
    "llb": "bachelor of laws",
    "mba": "master of business administration",
    "btech": "bachelor of technology",
    "mtech": "master of technology",
    "phd": "doctor of philosophy",
    "iti": "industrial training institute",
    "ece": "electronics and communication engineering",
    "cse": "computer science engineering",
    "eee": "electrical and electronics engineering",

    # Condition / Quality
    "refurb": "refurbished",
    "oem": "original equipment manufacturer",
    "diy": "do it yourself",
    "nib": "new in box",
    "nwt": "new with tags",
    "nwot": "new without tags",
    "bnib": "brand new in box",
    "nos": "new old stock",
    "eol": "end of life",

    # Units / Measurements
    "kg": "kilogram",
    "gm": "gram",
    "lb": "pound",
    "lbs": "pounds",
    "oz": "ounce",
    "km": "kilometer",
    "mi": "mile",
    "cm": "centimeter",
    "mm": "millimeter",
    "ft": "feet",
    "in": "inch",
    "l": "liter",
    "ml": "milliliter",
    "gal": "gallon",
    "hp": "horsepower",
    "bhp": "brake horsepower",
    "kw": "kilowatt",
    "kwh": "kilowatt hour",
    "v": "volt",
    "amp": "ampere",
    "w": "watt",
    "mah": "milliampere hour",

    # Business / Commerce
    "gst": "goods and services tax",
    "vat": "value added tax",
    "mrp": "maximum retail price",
    "msrp": "manufacturer suggested retail price",
    "rrp": "recommended retail price",
    "cod": "cash on delivery",
    "sku": "stock keeping unit",
    "roi": "return on investment",
    "b2b": "business to business",
    "b2c": "business to consumer",
    "c2c": "consumer to consumer",
    "pos": "point of sale",
    "crm": "customer relationship management",
    "erp": "enterprise resource planning",

    # Connectivity / Telecom
    "4g": "fourth generation",
    "5g": "fifth generation",
    "lte": "long term evolution",
    "sim": "subscriber identity module",
    "voip": "voice over internet protocol",
    "vpn": "virtual private network",
    "isp": "internet service provider",
    "adsl": "asymmetric digital subscriber line",
    "ftth": "fiber to the home",

    # Miscellaneous
    "dob": "date of birth",
    "id": "identification",
    "atm": "automated teller machine",
    "cctv": "closed circuit television",
    "rto": "regional transport office",
    "rc": "registration certificate",
    "dl": "driving license",
    "pan": "permanent account number",
    "aadhar": "aadhaar",
    "otp": "one time password",
    "upi": "unified payments interface",
    "neft": "national electronic funds transfer",
    "rtgs": "real time gross settlement",
    "ifsc": "indian financial system code",

    # Size abbreviations
    "xs": "extra small",
    "sm": "small",
    "md": "medium",
    "lg": "large",
    "xl": "extra large",
    "xxl": "extra extra large",
    "xxxl": "extra extra extra large",

    # Furniture / Household
    "l-shaped": "l shaped",
    "u-shaped": "u shaped",
    "diy": "do it yourself",
    "mdf": "medium density fiberboard",
    "plb": "plywood board",
    "ss": "stainless steel",
    "gi": "galvanized iron",
    "ms": "mild steel",
    "frp": "fiber reinforced plastic",
    "pvc": "polyvinyl chloride",
    "upvc": "unplasticized polyvinyl chloride",
    "cpvc": "chlorinated polyvinyl chloride",
    "hdpe": "high density polyethylene",
    "ldpe": "low density polyethylene",

    # Food / Kitchen
    "msg": "monosodium glutamate",
    "gmo": "genetically modified organism",

    # Fitness / Health
    "bmi": "body mass index",
    "bmr": "basal metabolic rate",
    "hiit": "high intensity interval training",
    "pt": "personal trainer",

    # Photography
    "dslr": "digital single lens reflex",
    "slr": "single lens reflex",

    # Audio
    "tws": "true wireless stereo",
    "anc": "active noise cancellation",
    "enc": "environmental noise cancellation",
    "dac": "digital to analog converter",
    "amp": "amplifier",

    # Ordinal-based
    "1st": "first",
    "2nd": "second",
    "3rd": "third",
    "4th": "fourth",
    "5th": "fifth",
}
