"""
Demonym -> country/region mappings for preprocessing.

Applied only when attribute_key is in a nationality/origin/country context.
Keys are lowercased demonyms, values are the canonical country/region name.
"""

DEMONYMS = {
    # South Asia
    "indian": "india",
    "pakistani": "pakistan",
    "bangladeshi": "bangladesh",
    "sri lankan": "sri lanka",
    "srilankan": "sri lanka",
    "nepali": "nepal",
    "nepalese": "nepal",
    "bhutanese": "bhutan",
    "maldivian": "maldives",
    "afghan": "afghanistan",

    # East Asia
    "chinese": "china",
    "japanese": "japan",
    "korean": "south korea",
    "south korean": "south korea",
    "north korean": "north korea",
    "taiwanese": "taiwan",
    "mongolian": "mongolia",

    # Southeast Asia
    "thai": "thailand",
    "vietnamese": "vietnam",
    "filipino": "philippines",
    "filipina": "philippines",
    "malaysian": "malaysia",
    "indonesian": "indonesia",
    "singaporean": "singapore",
    "burmese": "myanmar",
    "cambodian": "cambodia",
    "laotian": "laos",

    # Middle East
    "emirati": "united arab emirates",
    "saudi": "saudi arabia",
    "saudi arabian": "saudi arabia",
    "qatari": "qatar",
    "kuwaiti": "kuwait",
    "bahraini": "bahrain",
    "omani": "oman",
    "iraqi": "iraq",
    "iranian": "iran",
    "persian": "iran",
    "syrian": "syria",
    "lebanese": "lebanon",
    "jordanian": "jordan",
    "yemeni": "yemen",
    "israeli": "israel",
    "palestinian": "palestine",
    "turkish": "turkey",

    # Europe - Western
    "british": "united kingdom",
    "english": "england",
    "scottish": "scotland",
    "welsh": "wales",
    "irish": "ireland",
    "french": "france",
    "german": "germany",
    "dutch": "netherlands",
    "belgian": "belgium",
    "luxembourgish": "luxembourg",
    "swiss": "switzerland",
    "austrian": "austria",

    # Europe - Southern
    "italian": "italy",
    "spanish": "spain",
    "portuguese": "portugal",
    "greek": "greece",
    "maltese": "malta",
    "cypriot": "cyprus",

    # Europe - Northern
    "swedish": "sweden",
    "norwegian": "norway",
    "danish": "denmark",
    "finnish": "finland",
    "icelandic": "iceland",

    # Europe - Eastern
    "russian": "russia",
    "ukrainian": "ukraine",
    "polish": "poland",
    "czech": "czech republic",
    "slovak": "slovakia",
    "hungarian": "hungary",
    "romanian": "romania",
    "bulgarian": "bulgaria",
    "serbian": "serbia",
    "croatian": "croatia",
    "slovenian": "slovenia",
    "bosnian": "bosnia and herzegovina",
    "albanian": "albania",
    "macedonian": "north macedonia",
    "montenegrin": "montenegro",
    "estonian": "estonia",
    "latvian": "latvia",
    "lithuanian": "lithuania",
    "belarusian": "belarus",
    "moldovan": "moldova",
    "georgian": "georgia",
    "armenian": "armenia",
    "azerbaijani": "azerbaijan",

    # North America
    "american": "united states",
    "canadian": "canada",
    "mexican": "mexico",
    "cuban": "cuba",
    "jamaican": "jamaica",
    "haitian": "haiti",
    "dominican": "dominican republic",
    "puerto rican": "puerto rico",
    "trinidadian": "trinidad and tobago",
    "barbadian": "barbados",
    "guatemalan": "guatemala",
    "honduran": "honduras",
    "salvadoran": "el salvador",
    "nicaraguan": "nicaragua",
    "costa rican": "costa rica",
    "panamanian": "panama",

    # South America
    "brazilian": "brazil",
    "argentinian": "argentina",
    "argentine": "argentina",
    "colombian": "colombia",
    "venezuelan": "venezuela",
    "peruvian": "peru",
    "chilean": "chile",
    "ecuadorian": "ecuador",
    "bolivian": "bolivia",
    "paraguayan": "paraguay",
    "uruguayan": "uruguay",
    "guyanese": "guyana",
    "surinamese": "suriname",

    # Africa - North
    "egyptian": "egypt",
    "libyan": "libya",
    "tunisian": "tunisia",
    "algerian": "algeria",
    "moroccan": "morocco",
    "sudanese": "sudan",

    # Africa - West
    "nigerian": "nigeria",
    "ghanaian": "ghana",
    "senegalese": "senegal",
    "ivorian": "ivory coast",
    "malian": "mali",
    "cameroonian": "cameroon",

    # Africa - East
    "kenyan": "kenya",
    "ethiopian": "ethiopia",
    "tanzanian": "tanzania",
    "ugandan": "uganda",
    "rwandan": "rwanda",
    "somali": "somalia",
    "eritrean": "eritrea",

    # Africa - Southern
    "south african": "south africa",
    "zimbabwean": "zimbabwe",
    "zambian": "zambia",
    "mozambican": "mozambique",
    "namibian": "namibia",
    "botswanan": "botswana",
    "malagasy": "madagascar",
    "mauritian": "mauritius",

    # Oceania
    "australian": "australia",
    "new zealander": "new zealand",
    "kiwi": "new zealand",
    "fijian": "fiji",
    "samoan": "samoa",
    "tongan": "tonga",
    "papuan": "papua new guinea",

    # Indian states (common in Indian marketplace context)
    "kannadiga": "karnataka",
    "tamilian": "tamil nadu",
    "tamil": "tamil nadu",
    "malayali": "kerala",
    "telugu": "andhra pradesh",
    "marathi": "maharashtra",
    "gujarati": "gujarat",
    "punjabi": "punjab",
    "bengali": "west bengal",
    "bihari": "bihar",
    "rajasthani": "rajasthan",
    "assamese": "assam",
    "odia": "odisha",
    "kashmiri": "kashmir",
    "goan": "goa",
    "himachali": "himachal pradesh",
    "haryanvi": "haryana",
    "manipuri": "manipur",
    "naga": "nagaland",
    "mizo": "mizoram",
    "sikkimese": "sikkim",
}
